apiVersion: skaffold/v4beta11
kind: Config
metadata:
  name: sample-spring-boot-web-with-db

build:
  artifacts:
    - image: sample-spring-boot-web-with-db
      jib:
        project: com.example:sample-spring-boot-web-with-db
        args:
          - -DskipTests

deploy:
  kubectl:
    manifests:
      - k8s/configmap.yaml
      - k8s/secret.yaml
      - k8s/postgres-deployment.yaml
      - k8s/deployment.yaml
      - k8s/service.yaml

portForward:
  - resourceType: service
    resourceName: sample-spring-boot-app
    port: 80
    localPort: 8080
